### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by 394988736** [masastack/MASA.Blazor.Pro#197]
### Description

当启动时浏览器非最大化，然后切换到最大化窗口时，页面显示会变形
![image](https://github.com/masastack/MASA.Blazor.Pro/assets/81234257/2e5c0925-5670-4240-aa88-2496dbd55a1d)

**Comment by capdiem** [comment]
duplicate of https://github.com/masastack/MASA.Blazor/issues/1441
